      - name: Build Android APK (Local)
        run: |
          # Gereksiz parmak izi hesaplamasını atlayıp süreci hızlandırır
          export EAS_SKIP_AUTO_FINGERPRINT=1
          
          eas build \
            --platform android \
            --profile production \
            --local \
            --non-interactive \
            --verbose
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_PROJECT_CONFIG_V2: >
            {
              "android": {
                "keystore": {
                  "keystorePath": "./release.jks",
                  "keystorePassword": "${{ secrets.KEYSTORE_PASSWORD }}",
                  "keyAlias": "${{ secrets.KEYSTORE_ALIAS }}",
                  "keyPassword": "${{ secrets.KEY_PASSWORD }}"
                }
              }
            }
          NODE_OPTIONS: "--max-old-space-size=4096"
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
